from itertools import pairwise
from typing import Iterator


def pascals_triangle() -> Iterator[list]:
    """Generates an infinite sequence of rows of Pascal's triangle.

    At first generates the first row of Pascal's triangle with one element '1'.
    Then it yields the second row of Pascal's triangle with two elements: '1' and '1'.
    Each subsequent row is generated by summing adjacent elements of the previous row, with '1' added at both ends.
    This process continues infinitely.

    Yields:
        list: Infinite sequence of rows of Pascal's triangle.
    """
    row = [1]
    while True:
        yield row
        new_row = [1]
        for a, b in pairwise(row):
            new_row.append(a + b)
        new_row.append(1)
        row = new_row


if __name__ == "__main__":
    gen = pascals_triangle()
    for _ in range(5):
        print(next(gen))
